[mypy]
python_version = 3.11
strict = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
no_implicit_optional = true
show_error_codes = true
pretty = true
ignore_missing_imports = true
;explicit_package_bases = true
;namespace_packages = true
;no_site_packages = true

[mypy-tests.*]
ignore_errors = true

[mypy-quantum.*.tests.*]
ignore_errors = true
